apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: nginx-vm
  labels:
    app: nginx
    role: frontend
    ansible-managed: "true"
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: nginx-vm-root
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
  template:
    metadata:
      labels:
        app: nginx
        role: frontend
        ansible-managed: "true"
    spec:
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: vm-ssh-keys
            propagationMethod:
              noCloud: {}
      domain:
        cpu:
          cores: 1
        memory:
          guest: 2Gi
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
          rng: {}
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        dataVolume:
          name: nginx-vm-root
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            hostname: nginx-vm
            user: fedora
            packages:
              - python3
            runcmd:
              - systemctl enable --now sshd